### DISCUSSION TITLE
文章过期提醒貌似不生效

### DISCUSSION THREAD

**Discussion by MisakaTAT** [MaLuns/hexo-theme-async#126] [Q&A 疑难杂症] [answered]
在 `_config.async.yml` 配置了过期提醒，但是文章页面好像未生效，console 也没有报错。请问下是还需要其他配置或额外的插件支持嘛？

配置如下：
```yml
notice_outdate:
  enable: true
  style: flat
  limit_day: 365
  position: top
```
