### DISCUSSION TITLE
希望的更新

### DISCUSSION THREAD

**Discussion by Marweey** [MaLuns/hexo-theme-async#40] [Q&A 疑难杂症] [answered]
很希望能更新您页面左上角展示的访客计数！感谢感谢！很期待！

**Comment by MaLuns** [comment, marked as answer]
访客统计，可以前往 [https://count.getloli.com]( https://count.getloli.com) 查看。

感觉这是比较个性化需求了，就不加到通用版本里了，不过你可以按照下面方式，进行覆盖来实现

在你的 source\_data\style\index.less 文件里增加如下代码：

``` less
 // 如果文件不存在请新建

.trm-top-bar {
    .container {
        .trm-left-side {

            .trm-logo-frame {
                width          : 100% !important;
                justify-content: center;

                img {
                    height: 70%;
                    width : auto !important;
                }
            }
        }
    }
}
```

然后修改你 _config.async.yml 配置文件
``` ymal
user:
  # 注释掉这两个值
  first_name: #苍狗
  last_name: #白云

favicon:
  # 替换logo 为访客统计地址
  logo: https://count.getloli.com/get/@随便取个唯一值?theme=rule34
```
