### DISCUSSION TITLE
首页logo的问题

### DISCUSSION THREAD

**Discussion by aicsuk** [MaLuns/hexo-theme-async#52] [Q&A 疑难杂症] [answered]
发现一个bug
我配置好logo之后，首页顶部会像这样出现两个logo
![T}T}_E38`R}~DQ7`FJR)DTP](https://user-images.githubusercontent.com/60846054/210690005-deeb798d-0bdc-4ff1-ad5c-4377f8dc9d94.png)
然后我在 themes\async\layout\_partial 文件夹下的 header.ejs 里，删掉选择的这段代码后就好了
![I(ZLWBM{OB~V6LRD16AAJ_S](https://user-images.githubusercontent.com/60846054/210690450-68d4a9a1-cf05-4dac-b665-5dcae3a5b9e5.png)

**Comment by MaLuns** [comment, marked as answer]
是这样设计的，默认情况下是这样的

![image](https://user-images.githubusercontent.com/31614024/210691900-b0b4c156-47ef-4e3d-9756-d6d717f62072.png)

你可以 [参考文档](https://hexo-theme-async.imalun.com/guide/config.html#%E7%94%A8%E6%88%B7%E4%BF%A1%E6%81%AF-user) 进行调整

``` yaml
user:
  first_name: 
  last_name: 
```

**Reply by aicsuk** [reply]
好吧，之前我把这两个给注释了，所以才出现这样的问题。
另外，怎么设置手机端不显示logo呢？我看你的主页用手机访问就没有logo

**Reply by MaLuns** [reply]
``` less
@media(max-width:1200px) {
    .trm-logo-frame {
        img {
            display: none;
        }
    }
}
```
