### DISCUSSION TITLE
请教一下问题

### DISCUSSION THREAD

**Discussion by narwhrl** [MaLuns/hexo-theme-async#57] [Q&A 疑难杂症] [answered]
1. 主题的logo似乎限定了宽度，使用过宽的图片会把logo缩的很小，想问一下该如何解决？
2. 看到作者大佬的博客主题色似乎不一样？想知道主题颜色该如何更改
3. 默认博客主页的文章列表排版是双栏的
![image](https://user-images.githubusercontent.com/78220282/213993431-6adcd85d-3dc5-4739-812a-c549c2233e65.png)
作者以及示例博客的文章排版都是单栏的，想知道是如何切换的？
![image](https://user-images.githubusercontent.com/78220282/213993314-3e1aaf42-2e9e-4cee-accf-53b3c19b479b.png)

**Comment by MaLuns** [comment, marked as answer]
1,2 可以通过自定义样式进行覆盖，主题配色使用 css 变量控制的，[可以查看这里](https://github.com/MaLuns/hexo-theme-async/blob/dev/package/hexo-theme-async/source/css/_variables/index.less)
3 使用自定义模版功能，还没发布

**Reply by narwhrl** [reply]
好的，非常感谢！

**Reply by narwhrl** [reply]
很抱歉打扰了，我把您给的示例index.less文件内的css代码复制进了自己路径的/node_modules/hexo-theme-async/source/css/_variables/index.less文件中，hexo cl && hexo g 后页面的主题配色还是没有发生变化...
另外我想通过强制修改.trm-light-icon类以及.trm-dark-icon类的宽度来达到放大logo的目的，
```
.trm-light-icon {
    width=100% !important;
}

.trm-dark-icon {
    width=100% !important;
}
```
无论是放在/css/index.less还是/css/_variables/index.less中均造成了渲染错误，报错如图
![image](https://user-images.githubusercontent.com/78220282/214283157-a40bb116-048a-44f9-8b77-d6284ead6e88.png)

我对css的了解程度还不够，也很难研究透主题文件，还请麻烦您辛苦指教了~

**Reply by MaLuns** [reply]
> 很抱歉打扰了，我把您给的示例index.less文件内的css代码复制进了自己路径的/node_modules/hexo-theme-async/source/css/_variables/index.less文件中，hexo cl && hexo g 后页面的主题配色还是没有发生变化... 另外我想通过强制修改.trm-light-icon类以及.trm-dark-icon类的宽度来达到放大logo的目的，
> 
> ```
> .trm-light-icon {
>     width=100% !important;
> }
> 
> .trm-dark-icon {
>     width=100% !important;
> }
> ```
> 
> 无论是放在/css/index.less还是/css/_variables/index.less中均造成了渲染错误，报错如图 ![image](https://user-images.githubusercontent.com/78220282/214283157-a40bb116-048a-44f9-8b77-d6284ead6e88.png)
> 
> 我对css的了解程度还不够，也很难研究透主题文件，还请麻烦您辛苦指教了~

路径是这样的 source/_data/style/index.less，修改 logo 宽度示例

``` less
.trm-top-bar {
    .container {
        .trm-left-side {
            .trm-logo-frame {
                width          : 100% !important;
                justify-content: center;

                img {
                    height: 70%;
                    width : auto !important;
                }
            }
        }
    }
}
```
