### ISSUE TITLE
[Bug]: Twikoo 评论设置页面与页面元素错位

### ISSUE THREAD

**Issue by GrainRainy** [MaLuns/hexo-theme-async#101]
### 使用的 Hexo-Theme-Asycn 版本？ | What version of Hexo-Theme-Asycn are you use?

newest

### 是否修改过主题文件？ || Has the theme files been modified?

是 (Yes)

### 使用的浏览器？ || What browse are you using?

Chrome

### 使用的系統？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

感觉是主题适配的问题. 

![image](https://github.com/MaLuns/hexo-theme-async/assets/77619434/31b8b310-0d62-4a68-9c94-c9a5ddd403e6)

### 出现问题网站 | Website

grainrain.site

**Comment by MaLuns** [comment]
下个小版本修复下

**Comment by MaLuns** [comment]
试试这个样式
```css
.tk-admin-container {
	position: fixed !important;
	z-index: 100;
}
```
