### ISSUE TITLE
[Bug]:tags页面默认banner问题

### ISSUE THREAD

**Issue by 1BIMU** [MaLuns/hexo-theme-async#147]
### 使用的 Hexo-Theme-Asycn 版本？ | What version of Hexo-Theme-Asycn are you use?

latest version

### 是否修改过主题文件？ || Has the theme files been modified?

是 (Yes)

### 使用的浏览器？ || What browse are you using?

Chrome

### 使用的系統？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

跟之前的问题一样，上次是分类页面会自动被渲染为归档页面的banner
这次是tags页面

### 出现问题网站 | Website

bimu.site

**Comment by 1BIMU** [comment]
https://github.com/MaLuns/hexo-theme-async/issues/140
这是上次的issue

**Comment by MaLuns** [comment]
上次增加了 category 和 tag 全局 banner 配置

示例: 
``` yml
banner:
  tag:
    banner_title: 自定义标题
    banner_text: Hi my new friend!
```
