### ISSUE TITLE
激活和离开时端口文字没有生效

### ISSUE THREAD

**Issue by dinghui40** [MaLuns/hexo-theme-async#35]
```
favicon:
  logo: favicon-32x32.png
  icon16: favicon-16x16.png 
  icon32: favicon-32x32.png
  appleTouchIcon: apple-touch-icon.png
  webmanifest: /site.webmanifest
  visibilitychange: true
  hidden: failure.ico
  show_text: (/≧▽≦/)咦！又好了！
  hide_text: (●—●)喔哟，崩溃啦！
```
我按照文档这样写的，但是没有生效，我还遇到了一些其他bug，您看到了可否回一下呢？（我非常喜欢这个主题）
