### ISSUE TITLE
关于markdown文章代码块以及长标题的美化建议

### ISSUE THREAD

**Issue by Alvin-YS** [MaLuns/hexo-theme-async#41]
考虑把主题的侧边栏以及主题的宽度加大一点?
文章代码块一行过长可能显示不全(适当增加点宽度怎么样?
markdown文章目录过长也导致目录文字显示不全(加宽一点侧边栏?

**Comment by MaLuns** [comment]
主题宽度可以自定义样式，进行覆盖，可以调整为你自己喜欢大小，主题是响应式的，如果只需要修改 PC 端
可以像如下覆盖
``` css
@media (min-width: 1600px) {
    .container {
        max-width: 1540px;
    }
}
```
其他尺寸设置
![image](https://user-images.githubusercontent.com/31614024/206682209-89a80572-fe07-4b36-b1a6-94e75972d83a.png)
